### ISSUE TITLE
what and where the modifications needed for multi-lingual data

### ISSUE THREAD

**Issue by MHuzaifaUmair** [konsalex/Airport-Autocomplete-JS#6]
I am trying to make autocomplete in multi-lingual but i didn't understand how i can do it not clear can anyone help me please

**Comment by konsalex** [comment]
Hey @MHuzaifaUmair ,

In order to provide multi-lingual data you need to provide a CSV like the Greek_names.csv that can be found inside the src/data_scripts folder.

This script will generate a new airport.json that will include your airports. Then we need to compile the code again.

Do you have a CSV with the following formatting?
